---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: reloader-operator
  labels:
    app.kubernetes.io/name: reloader
    app.kubernetes.io/component: operator

spec:
  replicas: 1
  revisionHistoryLimit: 3

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app.kubernetes.io/name: reloader
      app.kubernetes.io/component: operator

  template:
    metadata:
      labels:
        app.kubernetes.io/name: reloader
        app.kubernetes.io/component: operator

    spec:
      enableServiceLinks: false
      serviceAccountName: reloader-operator

      securityContext:
        runAsNonRoot: true
        runAsUser: 65534

      containers:
        - name: server
          image: reloader-operator
          imagePullPolicy: IfNotPresent

          envFrom:
            - configMapRef:
                name: reloader-operator

          ports:
            - name: http
              containerPort: 9090

          livenessProbe:
            httpGet:
              path: /metrics
              port: http

          readinessProbe:
            httpGet:
              path: /metrics
              port: http

          resources:
            requests:
              cpu: "0.1"
              memory: "64Mi"
            limits:
              cpu: "0.5"
              memory: "512Mi"

...
