---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yml
  - clusterrole.yml
  - clusterrolebinding.yml
  - deployment.yml

configMapGenerator:
  - name: reloader-operator
    options:
      labels:
        app.kubernetes.io/name: reloader
        app.kubernetes.io/component: operator
    literals: []

...
